=== cppavel/InfoManagementXML/XML/Shop.dtd
<!ELEMENT databaseShop (Shop*)>
<!ELEMENT Shop (Shop.name, Shop.products+, Shop.owner)>
<!ATTLIST Shop id CDATA #REQUIRED>
<!ELEMENT Shop.name (#PCDATA)
>
<!ELEMENT Shop.products (Product*)>
<!ELEMENT Product EMPTY>
<!ATTLIST Product refid CDATA #REQUIRED>
<!ELEMENT Shop.owner (Seller)>
<!ELEMENT Seller EMPTY>
<!ATTLIST Seller refid CDATA #REQUIRED>

=== cppavel/InfoManagementXML/XML/Shop.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE databaseShop SYSTEM "Shop.dtd">
<databaseShop>
	<Shop id="s1">
		<Shop.name> AmazonReseller </Shop.name>
		<Shop.products>
			<Product refid="p228"/>
			<Product refid="p1757"/>
		</Shop.products>
		<Shop.owner>
			<Seller refid="sl2"/>
		</Shop.owner>
	</Shop>
	<Shop id="s2">
		<Shop.name> AmazonReseller </Shop.name>
		<Shop.products>
			<Product refid="p1753"/>
			<Product refid="p1757"/>
		</Shop.products>
		<Shop.owner>
			<Seller refid="sl2"/>
		</Shop.owner>
	</Shop>
	<Shop id="s3">
		<Shop.name>Heavy Gym</Shop.name>
		<Shop.products>
			<Product refid="p991"/>
		</Shop.products>
		<Shop.owner>
			<Seller refid="sl1"/>
		</Shop.owner>
	</Shop>
	<Shop id="s4">
		<Shop.name>GardenWorkshop</Shop.name>
		<Shop.products>
			<Product refid="p123"/>
		</Shop.products>
		<Shop.owner>
			<Seller refid="sl1"/>
		</Shop.owner>
	</Shop>
</databaseShop>
